# Each Key:Value should be in the below format
#   Sleeper user_id: Venmo user_id

rgillies28: Ryan-Gillies
TomGill: Thomas-Gillies-4
dcuth: Dan-Cuthbert
aconstant10: Andrew-Constant
BobTheChamp2016: B-Ross
egillies21: Eric-Gillies
tevancho: tom-evancho
tflora: tflora
ChristianSwagner: ChristianWagner
S_Shaffer: Stephen-Shaffer-20
ConePollos: Alex-Cohen-21
bengalball: Leanne-Evancho